In [2]:
import pandas as pd

In [3]:
sample = pd.read_csv('/Users/superyao/project/kml/zengjunyao/data/idp_export_idp_25560202_提现团伙统计.csv')
print(sample.shape)

(483, 1)

In [4]:
sample

         userid
0    5248133582
1    4786416885
2    4917976750
3     210681723
4    5143012032
..          ...
478  3624833012
479  4834646603
480  4503899347
481  2427353691
482  5078318615

[483 rows x 1 columns]

In [3]:
feature = pd.read_csv('/Users/superyao/project/kml/zengjunyao/user_info_multi_tables_20260225_112727.csv')
feature

,is_gid_15d,user_name,applist,visitor_id,reg_day,upload_phone_cnt_7d,platform,photo_camera_upload_cnt_7d,is_v,city_name,...,ip,is_verified,province_name,charge_num,reg_date,is_new_device,device_brand,device_factor,fans_user_num,max_global_id
0,0,谢嘻嘻.,"58同城,Microsoft 365 (Office),QQ,QQ浏览器,东方财富,中国移动...",147659662,3757.258947,0,ANDROID_PHONE,0,0.0,柳州,...,111.55.10.171,1.0,广西,0.0,2015-11-09 17:47:07,0.0,huawei,"['','acCharger','batteryExcept','batteryExcept...",39.0,NaN
1,0,叶狸狐假面,"58同城,BOSS直聘,QQ浏览器,UC浏览器,UC浏览器极速版,WPS Office,七猫...",1058125676,2752.129236,0,ANDROID_PHONE,0,0.0,温州,...,39.182.37.152,1.0,浙江,0.0,2018-08-10 20:53:54,0.0,xiaomi,"['','brightExcept','brightException','icStatus...",6.0,0000000a488b225b
2,0,NaN,NaN,1058125676,NaN,0,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN
3,0,木头,"QQ,QQ浏览器,i 漫游,今日头条,今日头条极速版,天天有余,应用宝,微信,快手,快手极速...",4665208834,351.537488,0,ANDROID_PHONE,0,0.0,唐山,...,221.192.126.54,1.0,河北,0.0,2025-03-07 11:06:01,0.0,vivo,"['','acCharger','batteryExcept','batteryExcept...",12.0,000000007d831f2b
4,0,烤肉好吃,"58同城,HttpCanary,QQ浏览器,WPS Office,今日头条,去哪儿旅行,应用...",3005605831,1258.624757,0,ANDROID_PHONE,0,0.0,*,...,223.160.150.217,0.0,辽宁,0.0,2022-09-12 09:00:21,0.0,huawei,"['','acCharger','icStatus','netPackage','noLoc...",226.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,0,NaN,",58同城,UC浏览器,WPS Office,一念逍遥,京东,今日头条,今日头条极速版,优酷...",2193290065,NaN,0,ANDROID_PHONE,0,NaN,徐州,...,49.68.23.85,NaN,江苏,NaN,NaN,0.0,honor,"['','acCharger','noLockScreen','realModel']",NaN,0000000acab078da
473,0,平安幸福,NaN,2760311469,1460.217917,0,NaN,0,0.0,NaN,...,NaN,1.0,NaN,0.0,2022-02-22 18:46:12,NaN,NaN,[],2.0,NaN
474,0,7465潜水艇,"58同城,QQ,QQ浏览器,SakuraFrp 启动器,UC浏览器,WPS Office,中...",2666587594,1542.281481,0,ANDROID_PHONE,0,0.0,衡阳,...,39.144.191.137,0.0,湖南,0.0,2021-12-02 17:14:40,0.0,huawei,"['','acCharger','noLockScreen']",0.0,NaN
475,0,NaN,NaN,2666587594,NaN,0,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN
476,0,渔小妹,"58同城,QQ,QQ浏览器,WPS Office,京东,今日头条,优酷视频,喜马拉雅,好看视...",2721985020,1489.234711,0,ANDROID_PHONE,0,0.0,*,...,112.111.55.148,1.0,福建,0.0,2022-01-24 18:22:01,0.0,cmdc,"['','noLockScreen']",11.0,NaN

In [7]:
print(feature.shape)

(474, 29)

In [8]:
feature['device_factor']

0      ['','acCharger','batteryExcept','batteryExcept...
1                        ['','acCharger','noLockScreen']
2                                    ['','noLockScreen']
3                           ['','acCharger','developer']
4                                    ['','noLockScreen']
                             ...
469                                                   []
470                                  ['','noLockScreen']
471    ['','acCharger','batteryExcept','batteryExcept...
472                                                   []
473                      ['','developer','noLockScreen']
Name: device_factor, Length: 474, dtype: object